#!/usr/bin/env bash

function usage() {
    echo -n "Usage: systole-dev [COMMAND] [OPTION] args...

The centralised development tool for Systole. Each command has its own set of
options. Use its '--help' command for more information.

Commands:
    help                this page
    build               build a package in the systole channel

Example:
    systole-dev help
"
}

function usage-build() {
    echo -n "Usage: systole-dev build package-name [--default-options|OPTIONS]

Build a package in the guix-systole channel.

To see the OPTIONS, refer to the command 'guix build --help'. This command comes
with the flag '--default-options', which executes the following flags for guix
build: '--keep-failed --keep-going --no-grafts --rounds=1 --verbosity=3'.

Commands:
    help                this page

Example:
    # Build package slicer with no build options:
    systole-dev build slicer

    # Build package slicer with default build options
    systole-dev build slicer --default-options

    # Build package slicer with custom build options
    systole-dev build slicer --keep-failed --rounds=2
"   
}

function build() {
    if [ -z "$1" ] || [ "$1" == "help" ]; then
        usage-build
        return 0
    fi

    package="$1"
    shift

    if [ "$1" == "--default-options" ]; then
        args='--keep-failed --keep-going --no-grafts --rounds=1 --verbosity=3'
    else
        args="$@"
    fi

    rm -rf /tmp/guix-build-* && /usr/bin/guix build -L . "$1" "$args"
}

if [ -z "$1" ]; then
    usage
    exit 0
fi

# Parse COMMAND
case "$1" in
help )
    usage
    ;;
build )
    shift
    build "$@"
    ;;
* )
    echo "systole-dev: Unrecognized command $1. Use 'help' for commands"
    exit 1
esac
